---
title: "Sustainable Solutions as Adoption of Solar Powered Irrigation Pumps in Nepal’s Terai"
author: "Dan Oziel"  
date: "The Department of Poblic Policy, Tel-Aviv University"
output: pdf_document
---
"The Department of Poblic Policy, Tel-Aviv University"

## Title: Research topic
Approximately 40% of the world's population works and makes a living from agriculture when a rifle lives in poverty and some in poor nutrition and even hunger (UN, 2015)

In order to fight poverty and produce food security in the world, agricultural output in developing countries and especially the output of those small farmers must be increased.  This increase will improve the economic situation of the farmers, encourage socio-economic development and ensure food security for growing populations.  It is estimated that any 10% increase in agricultural yields simultaneously creates a 7% reduction in poverty in Africa and a decrease of more than 5% in Asia (UNEP, 2012).

Increasing production and food output in the coming years is a vital and even critical need for developing countries - especially for millions of smallholders farmers

There is a consensus that adopting irrigation technologies is one of the key steps needed to improve agricultural output.  Irrigation enables better crop production in each growing season. having a greater number of growing seasons per year and not just in the rainy season.  It also increases the ability of farmers to cope with climate change - including changing rainfall patterns and drought years (Alemayehu & Bewket, 2017; FAO, 2011).

Currently, most of the farming  in developing countries is Dryland farming - agriculture that relies on the rainy season. In South Asia - the Green Revolution has resulted in irrigation of 42% of cultivated areas. There are obstacles  of knowledge and cost that prevent small farmers from adopting irrigation technologies but the lack of proper infrastructure and access to water are the main problems ( Chuchird, 2017 )

Energy is needed to transport and supply water through an irrigation system. But as mentioned, many regions in developing countries are network disconnected areas. Solar Powered Irrigation Pumps is a possible solution . These systems can provide efficient, cost-effective and sustainable energy for distributed irrigation services for farmers not connected to the electricity grid and water infrastructure.

The benefits these systems offer include: a. At the local level - improving the income of farmers and their families. B. Improvement at the national level - with increased agricultural production and improved food security, which leads to an improvement in social welfare. Global level improvement - which is the adoption of efficient and ecological development patterns while avoiding the use of fossil fuels and independent of major infrastructure

  ------
  
  Many people around the world live in off-grid areas, the term 'off grid' means - without relying on national or regional infrastructure services such as the power grid, water or a central sewer system. This is common in rural areas in developing countries with far-reaching consequences. Not only for the survival, health, and quality of life of the populations living there - but also for the food security of the states. Indeed - the ability to grow agricultural produce sufficiently depends on regular water supply for irrigation throughout the year - and, for the most part, pumping and transporting water requires energy in the form of electricity or fossil fuels (Doig, 1999).
  
  The main focal points of farmers in network disconnected areas are irrigation systems and a power source to operate them. Irrigation reduces farmers' vulnerability to climate change (changing rainfall patterns) and allows crops to be maintained throughout the year. For this, the average farmer is required to have an irrigation system with small-scale water management technologies and direct access to the territories themselves. By using irrigation systems, activity can be increased in areas already used for agriculture. Furthermore, irrigation has the potential to expand the total amount of irrigated area. This is especially true in sub-Saharan Africa - where adopting irrigation practices can significantly reduce poverty and increase agricultural output. For example, dry-season irrigation can improve annual yields from 70% to 300% across sub-Saharan Africa (Giordano et al., 2012).
  
As mentioned earlier, the most efficient and possible way to move irrigation systems in disconnected areas is by utilizing solar energy. The scientific basis of converting solar energy into direct electric current (DC) through the use of photovoltaic (PV) technology has been known for almost 150 years. The first modern photovoltaic cell as we know it was first developed in 1954 in Bell Labs in the US. In 1958, the first satellite was powered by solar energy and launched into space (Easton & Votaw, 1959). Some of the first solar satellites are still operating today - proving the durability of the technology

The state of electricity in Nepal, how many people have access? Is electricity regular or disconnected? Number of large or small power plants? Etc. etc
The lack of electricity is one of the major barriers to slowing growth and development
The best answer might be to adopt non-network-dependent solutions (FAO, 2013).
Is solar power the solution in general and for farmers in particular
What is the area irrigated in Nepal and what is the potential for using solar power (Dagnachew et al., 2017)
Need to increase output due to population growth?
Existing Pump Status - Availability, Prices,
Is diesel use increased (Giordano and de Fraiture, 2014; Namara et al., 2014).

The use of motorized pumps in sub-Saharan Africa - pumping rivers, streams, reservoirs or groundwater - can increase cultivated areas and consequently increase annual income (Xie et al., 2014)
The high costs of fuels to operate these pumps are a barrier to technology adoption by small farmers (Amjath-Babu et al., 2016)
Therefore - in light of the current trend in which solar panels are becoming more efficient and affordable - there is widespread agreement that photovoltaic technologies offer applicable electricity supply solutions in rural areas - both for household and irrigation purposes (Chandel et al., 2015; Jäger-Waldau, 2017; Mohammed Wazed et al., 2018; Muhsen et al., 2017)
Recent research shows that PV-based solar pumping can be more economical in rural areas compared to fuel and electricity pumps thanks to the constant improvement of technology and reduced capital investment (Chandel et al., 2015; Mohammed Wazed et al., 2018; Burney and Naylor, 2012; Kamwamba -Mtethiwa et al., 2016) provided the water supply does meet demand (Muhsen et al., 2017; Odeh et al., 2006).

####Accessibility and financing in developing countries
Raising awareness that solar energy can be harnessed to the global agricultural production agenda - while paying attention to environmental considerations and sustainability - has led more and more countries and international agencies to devote resources to promoting solar systems for agriculture in recent years 2016).
 In developing countries there is difficulty in financing agricultural projects. Agricultural funding carries a number of risks keys loan terms because it is difficult to estimate the investment in agriculture under conditions of uncertainty. Uncertainty is associated with natural hazards which are a lack of rain, floods and crop diseases. In addition - risks of price and demand volatility and macroeconomic or policy risks (Hollinger, 2004) due to undeveloped rural infrastructure and population dispersal - there are difficulties in operating and high transaction costs - which also impedes funding (IFAD, 2009).
 

### NEPAL
solar power irrigation pumps (SPIPs) are a proven technology, and can potentially be game changer in Nepal's irrigation sector by providing clean irrigation yo millions of farmers • Farmers who have applied for SPIPs have more land, better access to irrigation and own more pumps on average. This shows farmers who are already practising irrigated agriculture
Are there any other technological alternatives that
will enable smallholder farmers to grow more crops
in a year by utilizing abundant groundwater without
polluting the environment? Solar powered irrigation
pumps (SPIPs) provide one such alternative. SPIPs
have been tested widely in the region and have
been found to be a technically proven and workable
solution for all categories of farmers
The next step is installation.   We have conducted technical and financial feasibility surveys and found that all except three farmers qualify, and will install 62 SPIPs in January 2017.
SPIPs will come with automated data monitoring systems that will enable us to monitor the functioning of pumps and also disable them should farmers default repayment of loan or rental fees.  
We have already conducted a baseline survey for all farmers who have applied for SPIPs. We will also conduct mid line and end line surveys (qualitative and quantitative) and capture the impact of these SPIPs on agricultural and livelihood outcomes like cropping intensity, cropping pattern, crop productivity, incomes and nutritional intake.

### Research Methodology

An measurements  array of before-and-after that uses different techniques to create a comparison group that is as close as possible to the treatment group. However, because the comparison group is created by creating similarities in observed variables chosen by the researcher (such as gender, age, income level, etc.),   it is assumed that the similarity between the groups will be smaller than that obtained by random alloca   tion that allows for similarity in all the observed variables. (And not only those selected by the researcher) and also in unobservable variables (such as motivations, aspirations, values that the researcher has no information about).
 
an measurement set of before-and-after that use different techniques to create a

### Research
sustainable solutions as adoption of solar powered irrigation pumps in Nepal’s Terai 
How to ensure affordable and sustainable access to agricultural water for farmers in Nepal's Terai 
Can SPIPs replace traditional irrigation pumps in a clean and cost effective way and positively impact livelihoods of small and women farmers in Terai?
–What are the impacts of SPIPs on cropping pattern; crop productivity; and farm incomes?
–What institutional and financial models are most effective to ensure access to SPIPs?
–What are the impacts of SPIP adoption on atmospheric pollution?
Piloting solar pumps: How?
•Preliminary surveys of agriculture and water use
•Setting up of 3 pilots with institutional variations
–Woman farmer now using small diesel pump
–Farmer cooperative now using large diesel pump
–Male farmer now using small electric pump
•Semi-rigorous study of pilots to draw lessons
•Setting up 20-30 pumps using an experimental design –with institutional and financial variations
•Rigorous impact evaluation studies
•Concrete recommendations on institutional and financial models most appropriate for Nepal for further up scaling
Saptari District in Nepal Terai
–Least household level electrification among all Terai Districts
–Largest area under vegetables among all districts in Nepal
–Widespread use of small and large diesel pumps for irrigation


Because the experiment is uncontrolled
We cannot be sure that the groups will be the same
The groups are unbalanced and not identical

Propensity Score Matching Methods for non-experimental causal studies
  
  
  
### Research hypotheses
 * saving in diesel costs
SIP farmers will have higher cropping intensity, especially, more area under winter and summer crops
SIP farmers will cultivate more water intensive crops ( e.g summer paddy, vegetables and aquaculture) that non SIP farmers
SIP farmers will have more income/profit from crops because of reduced diesel costs, even if productivity remains the same
Worth checking if their family members (women and children) consume more leafy vegetables etc. in the food consumption/nutrition section


## literature review


