
#Did you buy water for irrigation during May-2014 to May-2015?
table(Water_extraction_mechanism_I_Baseline_2018_$buy_water_for_irrigation_s)
table(Water_extraction_mechanism_I_Baseline_2018_$buy_water_for_irrigation_m)
table(Water_extraction_mechanism_I_Baseline_2018_$buy_water_for_irrigation_w)

#From how many farmers did you buy water in each season?
table(Water_extraction_mechanism_I_Baseline_2018_$farmers_water_bought_from_s)
table(Water_extraction_mechanism_I_Baseline_2018_$farmers_water_bought_from__m)
table(Water_extraction_mechanism_I_Baseline_2018_$farmers_water_bought_from__w)#8 Observations

#How many Bighas irrigated by water buying? …
summary(Water_extraction_mechanism_I_Baseline_2018_$kathas_servedby_water_buying_s)
summary(Water_extraction_mechanism_I_Baseline_2018_$kathas_servedby_water_buying_m)
summary(Water_extraction_mechanism_I_Baseline_2018_$kathas_servedby_water_buying_w)#8 Observations
<-Water_extraction_mechanism_I_Baseline_2018_$kathas_servedby_water_buying_s
  Water_extraction_mechanism_I_Baseline_2018_$kathas_servedby_water_buying_m
  Water_extraction_mechanism_I_Baseline_2018_$kathas_servedby_water_buying_w
summary()

#What is the total number of hours for irrigation?
summary(Water_extraction_mechanism_I_Baseline_2018_$total_hrs_of_irrigation_buy_s)
summary(Water_extraction_mechanism_I_Baseline_2018_$total_hrs_of_irrigation_buy_m)
summary(Water_extraction_mechanism_I_Baseline_2018_$total_hrs_of_irrigation_buy_w) #8 Observations

#Do you buy diesel/kerosene for the pump separately? [1= Yes and 2= No]
table(Water_extraction_mechanism_I_Baseline_2018_$buy_diesel_kerosene_separately_t) #m
table(Water_extraction_mechanism_I_Baseline_2018_$buy_diesel_kerosene_separately_n) #s
table(Water_extraction_mechanism_I_Baseline_2018_$buy_diesel_kerosene_separately_x) #w

table(Water_extraction_mechanism_I_Baseline_2018_$cost_per_liter_of_diesel_m)#16 obs
table(Water_extraction_mechanism_I_Baseline_2018_$cost_per_liter_of_diesel_s)#16 obs
table(Water_extraction_mechanism_I_Baseline_2018_$cost_per_liter_of_diesel_w)#6 obs

# type of pump the water is bought from s m w x bw1 bw2 bw3
Water_extraction_mechanism_I_Baseline_2018_$type_of_pump_water_buy_s_p1 #summer p1
Water_extraction_mechanism_I_Baseline_2018_$type_of_pump_water_is_buy_s_pa #p2
Water_extraction_mechanism_I_Baseline_2018_$type_of_pump_water_is_buy_s_pb #p3
table(Water_extraction_mechanism_I_Baseline_2018_$type_of_pump_water_is_buy_s_pb)

Water_extraction_mechanism_I_Baseline_2018_$type_of_pump_water_buy_m_p1 # (monsoon)_p1
Water_extraction_mechanism_I_Baseline_2018_$type_of_pump_water_is_buy_m_pa #p2
Water_extraction_mechanism_I_Baseline_2018_$type_of_pump_water_is_buy_m_pb #p3
table(Water_extraction_mechanism_I_Baseline_2018_$type_of_pump_water_buy_m_p1)

Water_extraction_mechanism_I_Baseline_2018_$type_of_pump_water_buy_w_p1# (winter)_p1
Water_extraction_mechanism_I_Baseline_2018_$type_of_pump_water_is_buy_w_pa #p2
Water_extraction_mechanism_I_Baseline_2018_$type_of_pump_water_is_buy_w_pb#p3
table(Water_extraction_mechanism_I_Baseline_2018_$type_of_pump_water_buy_w_p1)

#What price did you pay in each season for buying water? p2&p3-few obs
summary(Water_extraction_mechanism_I_Baseline_2018_$price_paid_forwater_buy_s_p1) #summer
<-Water_extraction_mechanism_I_Baseline_2018_$price_paid_forwater_buy_s_p1
Water_extraction_mechanism_I_Baseline_2018_$price_paid_forwater_buy_s_p2
Water_extraction_mechanism_I_Baseline_2018_$price_paid_forwater_buy_s_p3 #annual
summary()

Water_extraction_mechanism_I_Baseline_2018_$price_paid_forwater_buy_m_p1 #monsoon
Water_extraction_mechanism_I_Baseline_2018_$price_paid_forwater_buy_m_p1
Water_extraction_mechanism_I_Baseline_2018_$price_paid_forwater_buy_m_p2
Water_extraction_mechanism_I_Baseline_2018_$price_paid_forwater_buy_m_p3

qw<-Water_extraction_mechanism_I_Baseline_2018_$price_paid_forwater_buy_w_p1 #winter
as<-Water_extraction_mechanism_I_Baseline_2018_$price_paid_forwater_buy_m_p2
zx<-Water_extraction_mechanism_I_Baseline_2018_$price_paid_forwater_buy_m_p3











