# [6.1] How many bore wells (BW) do you own?-----
# RBS
table(Water_extraction_mechanism_Baseline_2018_$how_many_bore_wells_do_you_ow)
table(Water_extraction_mechanism_Endline_EPC_2019_$how_many_bore_wells_do_you_ow)
# saptari
table(Water_extraction_mechanism_Baseline_2017_$how_many_bore_wells_do_you_ow)
table(Water_extraction_mechanism_Midline_2018_$how_many_bore_wells_do_you_ow)
table(Water_extraction_mechanisms_Endline_2019_Saptari$how_many_bore_wells_do_you_ow)

# RBS
table(Water_extraction_mechanism_Baseline_2018_$)
table(Water_extraction_mechanism_Endline_EPC_2019_$)
# saptari
table(Water_extraction_mechanism_Baseline_2017_$)
table(Water_extraction_mechanism_Midline_2018_$)
table(Water_extraction_mechanisms_Endline_2019_Saptari$)